In [ ]:
!pip install google-analytics-data

In [2]:
import pandas as pd

In [ ]:
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    DateRange,
    Dimension,
    Metric,
    RunReportRequest,
)

def run_report_to_dataframe(property_id="*******", credentials_json_path='C:\\Users\\jgotte\\Desktop\\Anaconda Proyecto\\lithe-key-402312-f56e2eb9aff2.json'):
    client = BetaAnalyticsDataClient.from_service_account_json(credentials_json_path)

    request = RunReportRequest(
        property=f"properties/{property_id}",
        dimensions=[Dimension(name="city"),Dimension(name="country"),Dimension(name="date"), Dimension(name="continent")],
        metrics=[Metric(name="activeUsers"), Metric(name="sessions") , Metric(name="newUsers") , Metric(name="bounceRate") , Metric(name="screenPageViewsPerSession") ],
        date_ranges=[DateRange(start_date="2023-01-01", end_date="2023-11-22")],
    )
    response = client.run_report(request)

    dimensions_city = [row.dimension_values[0].value for row in response.rows]
    dimensions_country = [row.dimension_values[1].value for row in response.rows]
    dimensions_date = [row.dimension_values[2].value for row in response.rows]
    dimensions_continent = [row.dimension_values[3].value for row in response.rows]
    metrics_sesiones = [row.metric_values[1].value for row in response.rows]
    metrics = [row.metric_values[0].value for row in response.rows]
    metrics_NEW_USER = [row.metric_values[2].value for row in response.rows]
    metrics_bounce_rate = [row.metric_values[3].value for row in response.rows]
    metrics_pageviewspersession = [row.metric_values[4].value for row in response.rows]


    data = {'City': dimensions_city, 'country' :dimensions_country, 'date' :dimensions_date,'continent' : dimensions_continent     ,  'sessions' :metrics_sesiones ,
            'ActiveUsers': metrics, 'newUsers': metrics_NEW_USER , 'bounceRate':  metrics_bounce_rate , 'screenPageViewsPerSession':  metrics_pageviewspersession}

   
   
    df = pd.DataFrame(data)

    return df

if __name__ == "__main__":
    result_df = run_report_to_dataframe()
    print("DataFrame result:")
    print(result_df)

In [5]:
from datetime import datetime

result_df['IDPropertie'] = **** 
result_df['Campaing'] = *****
result_df['Date_insert'] = datetime.now()
result_df['Server'] = ****
result_df['NamePropertie'] = '****'
result_df

,City,country,date,continent,sessions,ActiveUsers,newUsers,bounceRate,screenPageViewsPerSession,IDPropertie,Campaing,Date_insert,Server,NamePropertie
0,San Miguel de Tucuman,Argentina,20230707,Americas,27,23,12,0.07407407407407407,4.2962962962962967,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4
1,San Miguel de Tucuman,Argentina,20230626,Americas,30,22,17,0.2,4.333333333333333,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4
2,San Miguel de Tucuman,Argentina,20230708,Americas,24,21,15,0.125,4.333333333333333,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4
3,San Miguel de Tucuman,Argentina,20230629,Americas,26,20,15,0.15384615384615385,4.2307692307692308,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4
4,San Miguel de Tucuman,Argentina,20230704,Americas,27,19,13,0.22222222222222221,3.7407407407407409,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,San Francisco,Argentina,20230727,Americas,1,0,0,1,1,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4
871,San Salvador de Jujuy,Argentina,20231007,Americas,1,0,0,1,1,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4
872,San Salvador de Jujuy,Argentina,20231121,Americas,1,0,0,1,1,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4
873,Santiago del Estero,Argentina,20230716,Americas,1,0,0,1,1,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4
874,Simpang Empat,Indonesia,20230905,Asia,1,0,0,1,1,295191992,2023600,2023-11-30 12:14:46.668171,600,REFINOR_GA4

In [6]:
import cx_Oracle
cx_Oracle.init_oracle_client(lib_dir=r"C:\Users\jgotte\Downloads\instantclient-basic-windows.x64-18.5.0.0.0dbru\instantclient_18_5")

In [7]:
username = "****"
password = "*****"
host = "****"
port = "****"
service_name = "*****"

dsn_tns = cx_Oracle.makedsn(host, port, service_name=service_name)

connection = cx_Oracle.connect(username, password, dsn_tns)

cursor = connection.cursor()

data_to_insert = [tuple(row) for row in result_df.values]

insert_query = "INSERT INTO BASE_STA.F_GA_REGION_USER  (CITY,	COUNTRY,	DATE_REGION_USER,	CONTINENT,	SESSIONS,	ACTIVEUSERS,	NEWUSERS,	BOUNCERATE,	SCREENPAGEVIEWSPERSESSION,	IDPROPERTIE,	CAMPAING,	DATE_INSERT,	SERVER,	NAMEPROPERTIE)VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12, :13, :14)"

cursor.executemany(insert_query, data_to_insert)

connection.commit()

cursor.close()

connection.close()